import { useEffect, useState } from "react";
import { ImagePlus, Trash2, X } from "lucide-react";
import { savinexaAPI } from "../../services/api.js";
const box={background:"white",border:"1px solid #eee4da",borderRadius:14,padding:18}; const input={width:"100%",boxSizing:"border-box",border:"1px solid #e3d8cc",borderRadius:8,padding:"10px 12px"}; const button={border:0,borderRadius:8,padding:"9px 13px",color:"white",background:"#885129",cursor:"pointer"};
const empty={name:"",slug:"",description:"",shortDescription:"",images:[],thumbnail:"",price:0,salePrice:"",currency:"INR",category:"general",featured:false,bestseller:false,newArrival:false,active:true,visibility:"public"};
export default function CatalogManager(){
 const [tab,setTab]=useState("products"),[products,setProducts]=useState([]),[categories,setCategories]=useState([]),[collections,setCollections]=useState([]),[form,setForm]=useState(empty),[category,setCategory]=useState({name:"",slug:"",description:"",image:""}),[collection,setCollection]=useState({name:"",slug:"",description:"",image:"",type:"custom"}),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const load=async()=>{const [p,c,l]=await Promise.all([savinexaAPI.products({limit:200}),savinexaAPI.categories(),savinexaAPI.collections()]);setProducts(p.data.products||[]);setCategories(c.data.categories||[]);setCollections(l.data.collections||[]);}; useEffect(()=>{load().catch((e)=>setMessage(e.response?.data?.message||"Catalog could not be loaded."));},[]);
 const upload=async(file,done)=>{if(!file)return;setBusy(true);try{const fd=new FormData();fd.append("image",file);const{data}=await savinexaAPI.uploadImage(fd);done(data.url);setMessage("Image uploaded.");}catch(e){setMessage(e.response?.data?.message||"Image upload failed.");}finally{setBusy(false);}};
 const saveProduct=async(e)=>{e.preventDefault();setBusy(true);try{const body={...form,price:Number(form.price)||0,salePrice:form.salePrice===""?undefined:Number(form.salePrice),thumbnail:form.thumbnail||form.images[0]||""};if(form._id)await savinexaAPI.updateProduct(form._id,body);else await savinexaAPI.createProduct(body);setForm(empty);await load();setMessage("Product saved.");}catch(e){setMessage(e.response?.data?.message||"Product could not be saved.");}finally{setBusy(false);}};
 const removeProduct=async(id)=>{setBusy(true);try{await savinexaAPI.deleteProduct(id);await load();setMessage("Product removed.");}catch(e){setMessage(e.response?.data?.message||"Product could not be deleted.");}finally{setBusy(false);}};
 const saveCategory=async(e)=>{e.preventDefault();setBusy(true);try{await savinexaAPI.createCategory(category);setCategory({name:"",slug:"",description:"",image:""});await load();setMessage("Category added.");}catch(e){setMessage(e.response?.data?.message||"Category could not be saved.");}finally{setBusy(false);}};
 const saveCollection=async(e)=>{e.preventDefault();setBusy(true);try{await savinexaAPI.createCollection(collection);setCollection({name:"",slug:"",description:"",image:"",type:"custom"});await load();setMessage("Collection added.");}catch(e){setMessage(e.response?.data?.message||"Collection could not be saved.");}finally{setBusy(false);}};
 const imageUpload=(onDone)=> <label title="Upload image" style={{...button,display:"inline-grid",placeItems:"center",width:64,height:64,boxSizing:"border-box"}}><ImagePlus/><input hidden type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={(e)=>upload(e.target.files?.[0],onDone)}/></label>;
 const imageField=(label,obj,setObj)=> <label style={{display:"grid",gap:6}}>{label}<input style={input} value={obj.image||""} onChange={(e)=>setObj({...obj,image:e.target.value})} placeholder="Image URL"/>{imageUpload((url)=>setObj((s)=>({...s,image:url})))}{obj.image&&<img src={obj.image} alt="Preview" style={{width:110,height:80,objectFit:"cover",borderRadius:8}}/>}</label>;
 const slug=(name)=>String(name).toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");
 const field=(label,value,onChange,type="text",required=false)=><label style={{display:"grid",gap:5}}>{label}<input required={required} type={type} style={input} value={value??""} onChange={(e)=>onChange(e.target.value)}/></label>;
 return <div style={{display:"grid",gap:14}}>{message&&<p role="status" style={{...box,color:"#634722"}}>{message}</p>}<nav style={{display:"flex",gap:7}}>{[["products","Products"],["categories","Categories"],["collections","Collections"]].map(([id,label])=><button key={id} style={{...button,background:tab===id?"#885129":"#e9dfd5",color:tab===id?"white":"#513722"}} onClick={()=>setTab(id)}>{label}</button>)}</nav>
 {tab==="products"&&<><section style={box}><h2>{form._id?"Edit product":"Add product"}</h2><form onSubmit={saveProduct} style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:10}}>{field("Name",form.name,(v)=>setForm({...form,name:v,slug:form._id?form.slug:slug(v)}),"text",true)}{field("URL slug",form.slug,(v)=>setForm({...form,slug:slug(v)}),"text",true)}{field("Category slug",form.category,(v)=>setForm({...form,category:v}))}{field("Price",form.price,(v)=>setForm({...form,price:v}),"number")}{field("Sale price",form.salePrice,(v)=>setForm({...form,salePrice:v}),"number")}{field("Short description",form.shortDescription,(v)=>setForm({...form,shortDescription:v}))}<label style={{display:"grid",gap:5,gridColumn:"1/-1"}}>Description<textarea style={input} rows={3} value={form.description} onChange={(e)=>setForm({...form,description:e.target.value})}/></label><div style={{gridColumn:"1/-1",display:"flex",gap:8,alignItems:"center",flexWrap:"wrap"}}><strong>Product gallery</strong>{form.images.map((url,i)=><span key={url+i} style={{position:"relative"}}><img src={url} alt="" style={{width:75,height:75,objectFit:"cover",borderRadius:8}}/><button type="button" onClick={()=>setForm({...form,images:form.images.filter((_,ix)=>ix!==i)})} style={{position:"absolute",top:0,right:0}}><X size={13}/></button></span>)}{imageUpload((url)=>setForm((s)=>({...s,images:[...s.images,url]})))}</div><label><input type="checkbox" checked={form.featured} onChange={(e)=>setForm({...form,featured:e.target.checked})}/> Feature on home</label><label><input type="checkbox" checked={form.active} onChange={(e)=>setForm({...form,active:e.target.checked,visibility:e.target.checked?"public":"hidden"})}/> Published</label><button disabled={busy} style={{...button,gridColumn:"1/-1"}}>{busy?"Saving…":"Save product"}</button>{form._id&&<button type="button" onClick={()=>setForm(empty)} style={{...button,background:"#806c58"}}>Cancel edit</button>}</form></section><section style={box}><h2>Products ({products.length})</h2>{products.map((p)=><article key={p._id} style={{display:"grid",gridTemplateColumns:"56px 1fr auto auto",alignItems:"center",gap:10,borderTop:"1px solid #eee4da",padding:"9px 0"}}><img src={p.images?.[0]||p.thumbnail||""} alt="" style={{width:54,height:54,objectFit:"cover",background:"#eee",borderRadius:7}}/><span><b>{p.name}</b><small style={{display:"block"}}>{p.slug} · {p.visibility}</small></span><button style={button} onClick={()=>{setForm({...empty,...p,images:p.images||[]});window.scrollTo({top:0,behavior:"smooth"});}}>Edit</button><button style={{...button,background:"#9c4e3f"}} onClick={()=>removeProduct(p._id)}><Trash2 size={15}/></button></article>)}</section></>}
 {tab==="categories"&&<><section style={box}><h2>Add category with image</h2><form onSubmit={saveCategory} style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:10}}>{field("Name",category.name,(v)=>setCategory({...category,name:v,slug:slug(v)}),"text",true)}{field("Slug",category.slug,(v)=>setCategory({...category,slug:slug(v)}),"text",true)}{field("Description",category.description,(v)=>setCategory({...category,description:v}))}{imageField("Category image",category,setCategory)}<button style={button}>Add category</button></form></section><section style={box}><h2>Current categories</h2>{categories.map((c)=><p key={c._id}>{c.name} · {c.slug}</p>)}</section></>}
 {tab==="collections"&&<><section style={box}><h2>Add collection with image</h2><form onSubmit={saveCollection} style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:10}}>{field("Name",collection.name,(v)=>setCollection({...collection,name:v,slug:slug(v)}),"text",true)}{field("Slug",collection.slug,(v)=>setCollection({...collection,slug:slug(v)}),"text",true)}{field("Description",collection.description,(v)=>setCollection({...collection,description:v}))}{imageField("Collection image",collection,setCollection)}<button style={button}>Add collection</button></form></section><section style={box}><h2>Current collections</h2>{collections.map((c)=><p key={c._id}>{c.name} · {c.slug}</p>)}</section></>}
 </div>;
}