import { useEffect, useState } from "react";
import { Save, Upload } from "lucide-react";
import { savinexaAPI } from "../../services/api.js";

const defaults = { siteName: "Savinexa", logo: "", favicon: "", primaryColor: "#1f2937", secondaryColor: "#eab308", background: "#f8fafc", typography: "Inter", borderRadius: "18px", hero: { eyebrow: "Premium lifestyle collection", title: "Savinexa", subtitle: "Curated essentials, elevated living, and product experiences designed for modern homes and premium lifestyles.", image: "", mobileImage: "", overlayColor: "#101828", overlayOpacity: .72, primaryCtaLabel: "Explore collection", primaryCtaUrl: "/savinexa/products", secondaryCtaLabel: "Shop Savitri Livings", secondaryCtaUrl: "/shop" }, homeSections: { featuredProducts: { enabled: true, title: "Featured products" }, categories: { enabled: true, title: "Shop by category" }, collections: { enabled: true, title: "Collections" } }, footer: { tagline: "Thoughtful finds for everyday living.", background: "#1f2937", textColor: "#ffffff" }, announcementBar: { enabled: false, text: "", link: "/" }, contact: {}, socialLinks: {}, seo: {} };
const box = { background: "white", border: "1px solid #eee4da", borderRadius: 14, padding: 18 };
const input = { width: "100%", boxSizing: "border-box", border: "1px solid #e3d8cc", borderRadius: 8, padding: "10px 12px", color: "#382719", background: "#fff" };
const button = { border: 0, borderRadius: 8, padding: "10px 14px", color: "white", background: "#885129", fontWeight: 650, cursor: "pointer" };

export default function WebsiteSettings() {
  const [settings, setSettings] = useState(defaults); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  useEffect(() => { savinexaAPI.settings().then(({ data }) => setSettings((s) => ({ ...s, ...data.settings, hero: { ...s.hero, ...data.settings?.hero }, homeSections: { ...s.homeSections, ...data.settings?.homeSections }, footer: { ...s.footer, ...data.settings?.footer } }))).catch((e) => setError(e.response?.data?.message || "Settings could not be loaded.")); }, []);
  const update = (path, value) => setSettings((s) => { const next = structuredClone(s); const parts = path.split("."); let node = next; parts.slice(0,-1).forEach((key) => { node[key] ||= {}; node = node[key]; }); node[parts.at(-1)] = value; return next; });
  const upload = async (file, done) => { if (!file) return; setBusy(true); setError(""); try { const form = new FormData(); form.append("image", file); const { data } = await savinexaAPI.uploadImage(form); done(data.url); setNotice("Image uploaded. Save website design to publish it."); } catch (e) { setError(e.response?.data?.message || "Image upload failed. Check media storage configuration."); } finally { setBusy(false); } };
  const save = async (e) => { e.preventDefault(); setBusy(true); setError(""); try { const { data } = await savinexaAPI.saveSettings(settings); setSettings((s) => ({ ...s, ...data.settings })); setNotice("SaviNexa website settings saved."); } catch (err) { setError(err.response?.data?.message || "Settings could not be saved."); } finally { setBusy(false); } };
  const field = (label,path,multiline=false) => <label key={path} style={{ display: "grid", gap: 6 }}>{label}{multiline ? <textarea rows={3} value={get(path) || ""} onChange={(e) => update(path,e.target.value)} style={{ ...input, resize: "vertical" }}/> : <input value={get(path) || ""} onChange={(e) => update(path,e.target.value)} style={input}/>}</label>;
  const get = (path) => path.split(".").reduce((v,k) => v?.[k],settings);
  const image = (label,path) => <label key={path} style={{ display: "grid", gap: 7, alignContent: "start" }}>{label}<input value={get(path)||""} onChange={(e)=>update(path,e.target.value)} placeholder="Image URL or upload" style={input}/><span style={{ display: "flex", gap: 8, alignItems: "center" }}><label style={{ ...button, display: "inline-flex", gap: 6, alignItems: "center" }}><Upload size={15}/>Upload<input hidden type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={(e)=>upload(e.target.files?.[0],(url)=>update(path,url))}/></label>{get(path) && <button type="button" style={{ ...button, background: "#806c58" }} onClick={()=>update(path,"")}>Remove</button>}</span>{get(path) && <img src={get(path)} alt={`${label} preview`} style={{ width: "100%", maxHeight: 200, objectFit: "contain", objectPosition: "left", background: "#f5f0e9", borderRadius: 8 }}/>}</label>;
  const color = (label,path) => <label key={path} style={{ display: "grid", gap: 6 }}>{label}<input type="color" value={get(path)||"#ffffff"} onChange={(e)=>update(path,e.target.value)} style={{ ...input, height: 43 }}/></label>;
  return <form onSubmit={save} style={{ display: "grid", gap: 14 }}>
    {error && <div role="alert" style={{ ...box, color: "#a33", background: "#fff7f5" }}>{error}</div>}{notice && <div role="status" style={{ ...box, color: "#375c30", background: "#f5fbf3" }}>{notice}</div>}
    <section style={box}><h2>Brand & theme</h2><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(220px,1fr))", gap: 12 }}>{field("Site name","siteName")}{color("Primary color","primaryColor")}{color("Accent color","secondaryColor")}{color("Background","background")}<label style={{ display:"grid",gap:6 }}>Typography<select value={settings.typography} onChange={(e)=>update("typography",e.target.value)} style={input}>{["Inter","Arial","Georgia","Poppins","DM Sans","Playfair Display"].map((x)=><option key={x}>{x}</option>)}</select></label>{field("Corner radius (e.g. 18px)","borderRadius")}{image("Logo","logo")}{image("Favicon","favicon")}</div></section>
    <section style={box}><h2>Homepage hero</h2><div style={{ display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(230px,1fr))",gap:12 }}>{field("Eyebrow","hero.eyebrow")}{field("Heading","hero.title")}{field("Description","hero.subtitle",true)}{image("Desktop hero image","hero.image")}{image("Mobile hero image","hero.mobileImage")}{color("Overlay color","hero.overlayColor")}<label style={{ display:"grid",gap:8 }}>Overlay strength<input type="range" min="0" max="1" step=".05" value={settings.hero.overlayOpacity} onChange={(e)=>update("hero.overlayOpacity",Number(e.target.value))}/></label>{field("Main button label","hero.primaryCtaLabel")}{field("Main button URL","hero.primaryCtaUrl")}{field("Second button label","hero.secondaryCtaLabel")}{field("Second button URL","hero.secondaryCtaUrl")}</div></section>
    <section style={box}><h2>Homepage sections</h2><div style={{ display:"grid",gap:10 }}>{[["featuredProducts","Featured products"],["categories","Categories"],["collections","Collections"]].map(([key,label])=><div key={key} style={{ display:"grid",gridTemplateColumns:"170px 1fr",gap:10,alignItems:"center" }}><label><input type="checkbox" checked={settings.homeSections[key]?.enabled!==false} onChange={(e)=>update(`homeSections.${key}.enabled`,e.target.checked)}/> Show {label}</label><input aria-label={`${label} heading`} value={settings.homeSections[key]?.title||""} onChange={(e)=>update(`homeSections.${key}.title`,e.target.value)} style={input}/></div>)}</div></section>
    <section style={box}><h2>Announcement, footer & SEO</h2><div style={{ display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:12 }}><label><input type="checkbox" checked={settings.announcementBar.enabled} onChange={(e)=>update("announcementBar.enabled",e.target.checked)}/> Show announcement bar</label>{field("Announcement text","announcementBar.text")}{field("Announcement link","announcementBar.link")}{field("Footer tagline","footer.tagline")}{color("Footer background","footer.background")}{color("Footer text","footer.textColor")}{field("Contact email","contact.email")}{field("Contact phone","contact.phone")}{field("Instagram URL","socialLinks.instagram")}{field("Facebook URL","socialLinks.facebook")}{field("SEO title","seo.defaultMetaTitle")}{field("SEO description","seo.defaultMetaDescription",true)}</div></section>
    <button disabled={busy} style={{ ...button, justifySelf:"start",display:"inline-flex",gap:8,alignItems:"center" }}><Save size={16}/>{busy?"Saving…":"Save website design"}</button>
  </form>;
}