import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowUpRight, Gem, Handshake, Megaphone, Rocket, GraduationCap, Store } from "lucide-react";
import { ecosystemAPI } from "../../services/api.js";

const icons = { "business-partnerships": Handshake, "sl-business": GraduationCap, "startup-support": Rocket, "future-integrations": ArrowUpRight };
const pillars = [
  [Gem, "Jewellery & fashion", "Discover and sell aesthetic, affordable jewellery made for everyday moments and celebrations."],
  [Store, "Home décor & lifestyle", "Find products that make everyday spaces more beautiful, meaningful and personal."],
  [Megaphone, "Marketplace & marketing", "Buy, sell and promote products through a connected local marketplace."],
];

export default function Ecosystem() {
  const [links, setLinks] = useState([]);
  useEffect(() => { ecosystemAPI.getAll().then(({ data }) => setLinks(data.links)).catch(() => {}); }, []);
  return <main style={{ background:"#fffaf3", minHeight:"100vh", padding:"6.5rem 1rem 4rem" }}><section style={{ maxWidth:1080, margin:"0 auto", textAlign:"center" }}><p className="section-tag">One connected ecosystem</p><h1 style={{ color:"#38250f", fontSize:"clamp(2.5rem,6vw,4.7rem)", margin:".6rem auto", maxWidth:800 }}>More than shopping. A place to build, grow and connect.</h1><p style={{ color:"#6e573a", lineHeight:1.8, maxWidth:720, margin:"1rem auto 0" }}>Savitri Livings brings lifestyle, commerce, business learning, marketing and partnerships under one welcoming umbrella for individuals, creators, students, startups and small businesses.</p><div style={{ display:"flex", justifyContent:"center", gap:10, flexWrap:"wrap", marginTop:24 }}><Link to="/marketplace" className="btn-terra">Explore marketplace</Link><Link to="/marketplace/sell" className="btn-outline">Start selling</Link></div></section><section style={{ maxWidth:1080, margin:"3.5rem auto", display:"grid", gridTemplateColumns:"repeat(3,1fr)", gap:16 }} className="ecosystem-pillars">{pillars.map(([Icon,title,text])=><article key={title} style={{ background:"white", border:"1px solid #eadbc6", borderRadius:16, padding:"1.5rem" }}><Icon size={25} color="#a66e28"/><h2 style={{ color:"#493015", fontSize:"1.45rem", margin:".85rem 0 .45rem" }}>{title}</h2><p style={{ color:"#80684b", lineHeight:1.7, fontSize:".9rem" }}>{text}</p></article>)}</section><section style={{ maxWidth:1080, margin:"0 auto" }}><p className="section-tag">Build with us</p><h2 style={{ color:"#38250f", fontSize:"2.3rem", margin:".4rem 0 1.2rem" }}>Spaces opening across Savitri Livings</h2><div style={{ display:"grid", gridTemplateColumns:"repeat(2,1fr)", gap:16 }} className="ecosystem-links">{links.map(link=>{const Icon=icons[link.key]||ArrowUpRight;const content=<><Icon size={22} color="#a66e28"/><h3 style={{color:"#493015",fontSize:"1.35rem",margin:".8rem 0 .35rem"}}>{link.title}</h3><p style={{color:"#80684b",lineHeight:1.65,fontSize:".88rem"}}>{link.description}</p><span style={{display:"inline-flex",gap:5,alignItems:"center",color:"#9d6a27",fontWeight:600,fontSize:".82rem",marginTop:14}}>{link.url?"Explore now":"Coming soon"}<ArrowUpRight size={14}/></span></>;return link.url?<a key={link.key} href={link.url} style={{textDecoration:"none",background:"#fdf5e9",border:"1px solid #e4cda7",borderRadius:16,padding:"1.5rem"}}>{content}</a>:<article key={link.key} style={{background:"#fdf5e9",border:"1px solid #e4cda7",borderRadius:16,padding:"1.5rem"}}>{content}</article>})}</div></section><style>{`@media(max-width:700px){.ecosystem-pillars,.ecosystem-links{grid-template-columns:1fr!important}}`}</style></main>;
}
