import { useEffect, useMemo, useState } from "react";
import { ArrowRight, Gem, GraduationCap, Handshake, Heart, Home as HomeIcon, Megaphone, Rocket, Search, ShoppingBag, Sparkles, Store, Truck, Users } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { marketplaceAPI, productAPI } from "../../services/api.js";
import { useCart } from "../../context/CartContext.jsx";
import { useCity } from "../../context/CityContext.jsx";

const fallback = "/brand/savitri-jewellers-earrings.png";
const departments = [[Gem,"Jewellery","/shop",fallback],[Heart,"Gifts","/shop?category=gift","/brand/savitri-jewellers-heart-earrings.png"],[HomeIcon,"Home décor","/marketplace","/brand/savitri-jewellers-heart-earrings.png"],[Store,"Marketplace","/marketplace",fallback],[Handshake,"Partners","/ecosystem","/brand/savitri-jewellers-heart-earrings.png"],[GraduationCap,"SL Business","/ecosystem",fallback]];
const offers = [[Gem,"Jewellery & Fashion","Discover and sell aesthetic and affordable jewellery.","/shop"],[HomeIcon,"Home Décor & Lifestyle","Products that make everyday spaces more beautiful and meaningful.","/marketplace"],[Store,"Marketplace","A platform where businesses and individuals can buy and sell products.","/marketplace"],[Handshake,"Business Partnerships","Connect brands, sellers, creators and potential business partners.","/ecosystem"],[Megaphone,"Marketing Support","Tools and opportunities to promote products, brands and businesses.","/ecosystem"],[GraduationCap,"SL Business","Practical learning for startups, small businesses, entrepreneurs and students.","/ecosystem"],[Rocket,"Startup Support","Resources and opportunities designed to help new businesses grow.","/ecosystem"],[Sparkles,"One Connected Ecosystem","Lifestyle, commerce, learning, marketing and partnerships under one umbrella.","/ecosystem"]];

function Heading({tag,title,to,label}) { return <div style={{display:"flex",justifyContent:"space-between",alignItems:"end",gap:14,flexWrap:"wrap",marginBottom:18}}><div><p className="section-tag">{tag}</p><h2 style={{fontSize:"clamp(1.9rem,4vw,2.8rem)",color:"#38250f"}}>{title}</h2></div>{to&&<Link to={to} style={{display:"inline-flex",gap:5,alignItems:"center",color:"#8d5d23",fontSize:".85rem",fontWeight:700}}>{label}<ArrowRight size={16}/></Link>}</div> }
function Product({product}) { const {addToCart}=useCart(); return <article style={{background:"white",border:"1px solid #eadbc7",borderRadius:14,overflow:"hidden",minWidth:0}}><Link to={`/product/${product._id}`} style={{display:"block",aspectRatio:"1",background:"#f7eddf",padding:8}}><img src={product.images?.[0]||fallback} alt={product.name} style={{width:"100%",height:"100%",objectFit:"contain"}}/></Link><div style={{padding:".75rem"}}><p style={{fontSize:".62rem",color:"#9d6a27",fontWeight:700,textTransform:"uppercase",letterSpacing:".1em"}}>{product.category||"Savitri find"}</p><Link to={`/product/${product._id}`}><h3 style={{fontFamily:"'DM Sans',sans-serif",fontSize:".85rem",lineHeight:1.4,minHeight:"2.45em",margin:".3rem 0",color:"#38250f",overflow:"hidden"}}>{product.name}</h3></Link><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><b style={{color:"#6e461c"}}>₹{Number(product.price||0).toLocaleString("en-IN")}</b><button onClick={()=>addToCart(product)} disabled={product.stock===0} aria-label="Add to cart" style={{width:31,height:31,border:0,borderRadius:8,display:"grid",placeItems:"center",background:"#765027",color:"white",cursor:"pointer"}}><ShoppingBag size={15}/></button></div></div></article> }
function Listing({listing}) { const image=listing.images?.[0]; return <Link to={`/marketplace/listing/${listing._id}`} style={{background:"white",border:"1px solid #eadbc7",borderRadius:14,overflow:"hidden",color:"inherit",minWidth:0}}><div style={{height:142,background:image?`#f7eddf url(${image}) center/contain no-repeat`:"#f7eddf",display:"grid",placeItems:"center"}}>{!image&&<Store color="#b18142" size={26}/>}</div><div style={{padding:".75rem"}}><p style={{fontSize:".62rem",color:"#9d6a27",fontWeight:700,textTransform:"uppercase",letterSpacing:".1em"}}>{listing.category}</p><h3 style={{fontFamily:"'DM Sans',sans-serif",fontSize:".85rem",lineHeight:1.4,minHeight:"2.45em",margin:".3rem 0",color:"#38250f",overflow:"hidden"}}>{listing.title}</h3><b style={{color:"#6e461c"}}>{listing.price==null?"Contact seller":`₹${Number(listing.price).toLocaleString("en-IN")}`}</b></div></Link> }

export default function Home() {
  const navigate=useNavigate(),{city}=useCity(); const [search,setSearch]=useState(""),[products,setProducts]=useState([]),[listings,setListings]=useState([]),[loading,setLoading]=useState(true);
  useEffect(()=>{let mounted=true;Promise.all([productAPI.getAll({city,limit:24}),marketplaceAPI.listings({limit:12})]).then(([p,l])=>{if(mounted){setProducts(p.data.products||[]);setListings(l.data.listings||[])}}).catch(()=>{}).finally(()=>mounted&&setLoading(false));return()=>{mounted=false}},[city]);
  const picks=useMemo(()=>[...products].sort(()=>Math.random()-.5).slice(0,8),[products]); const fresh=useMemo(()=>[...listings].sort(()=>Math.random()-.5).slice(0,5),[listings]);
  return <main style={{background:"#fffaf3",overflow:"hidden"}}>
    <section style={{padding:"5.7rem 1rem 1.2rem",background:"linear-gradient(135deg,#f8ead2,#f2d29b 52%,#e6b969)"}}><div style={{maxWidth:1180,margin:"0 auto"}}>
      <form onSubmit={e=>{e.preventDefault();navigate(search.trim()?`/shop?search=${encodeURIComponent(search.trim())}`:"/shop")}} style={{maxWidth:720,margin:"0 auto",padding:5,background:"white",borderRadius:12,display:"flex",boxShadow:"0 9px 24px rgba(95,61,20,.16)"}}><Search color="#896136" size={20} style={{margin:"0 9px",alignSelf:"center"}}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search jewellery, gifts, home décor and more" style={{width:"100%",border:0,outline:0,fontSize:16,padding:".8rem .2rem"}}/><button className="btn-terra" style={{minHeight:40,padding:"0 1rem",borderRadius:8}}>Search</button></form>
      <div className="home-departments" style={{display:"grid",gridTemplateColumns:"repeat(6,1fr)",gap:10,margin:"1rem 0"}}>{departments.map(([Icon,label,to,image])=><Link key={label} to={to} style={{background:"rgba(255,255,255,.82)",border:"1px solid rgba(143,96,35,.15)",borderRadius:12,padding:".65rem .35rem",textAlign:"center",color:"#513514"}}><img src={image} alt="" style={{width:42,height:42,objectFit:"contain",margin:"0 auto 4px"}}/><span style={{display:"block",fontSize:".7rem",fontWeight:700}}><Icon size={11} style={{verticalAlign:"-1px",marginRight:2}}/>{label}</span></Link>)}</div>
      <div className="home-hero" style={{display:"grid",gridTemplateColumns:"1.15fr .85fr",gap:18,marginTop:18}}><div style={{background:"linear-gradient(115deg,#593918,#8b5b20 62%,#c89449)",borderRadius:18,padding:"clamp(1.6rem,4vw,3.3rem)",color:"#fffaf3"}}><p style={{color:"#f6d88e",fontSize:".72rem",fontWeight:700,letterSpacing:".15em",textTransform:"uppercase"}}>Savitri Livings marketplace</p><h1 style={{fontSize:"clamp(2.5rem,5vw,4.5rem)",lineHeight:.96,margin:".65rem 0 1rem",maxWidth:560}}>Discover pieces, people and possibilities.</h1><p style={{color:"#f8e7c8",lineHeight:1.7,maxWidth:515}}>Shop jewellery and lifestyle finds, sell through Thikana, and grow with a connected business ecosystem.</p><div style={{display:"flex",gap:10,flexWrap:"wrap",marginTop:22}}><Link to="/shop" className="btn-terra" style={{background:"#fff9ee",color:"#6d461b"}}>Shop Savitri finds <ArrowRight size={16}/></Link><Link to="/marketplace" className="btn-outline" style={{borderColor:"#f5d48f",color:"#fff9ee"}}>Explore Thikana</Link></div></div><div style={{background:"#fffdf9",border:"1px solid #e3c998",borderRadius:18,overflow:"hidden",padding:10}}><img src="/brand/savitri-jewellers-heart-earrings.png" alt="Savitri Livings jewellery" style={{width:"100%",height:220,objectFit:"contain",background:"#f6ead8",borderRadius:12}}/><div style={{padding:".8rem .4rem"}}><p className="section-tag">Something special</p><h2 style={{fontSize:"1.65rem",color:"#493015"}}>Jewellery, gifting & more</h2><p style={{fontSize:".82rem",color:"#80684b",marginTop:4}}>Made to brighten everyday moments.</p></div></div></div>
    </div></section>
    <section style={{padding:"1.25rem 1rem",background:"white"}}><div className="home-assurance" style={{maxWidth:1180,margin:"0 auto",display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:12}}>{[[Truck,"Thoughtful delivery","Carefully packed orders"],[Users,"Sell with Thikana","Start your seller journey"],[Sparkles,"Build with Savitri","Learning and opportunities"]].map(([Icon,title,text])=><div key={title} style={{display:"flex",justifyContent:"center",alignItems:"center",gap:9,color:"#5c3d1a"}}><Icon size={20} color="#a26c26"/><div><b style={{fontSize:".78rem",display:"block"}}>{title}</b><span style={{fontSize:".7rem",color:"#95734c"}}>{text}</span></div></div>)}</div></section>
    <section style={{padding:"3.5rem 1rem",maxWidth:1180,margin:"0 auto"}}><Heading tag="Picked for you" title="Shop Savitri Livings favourites" to="/shop" label="View all jewellery"/>{loading?<p style={{color:"#80684b"}}>Loading products…</p>:picks.length?<div className="home-product-grid" style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:14}}>{picks.map(product=><Product key={product._id} product={product}/>)}</div>:<div style={{padding:28,background:"white",borderRadius:14,color:"#80684b"}}>New Savitri Livings products will appear here soon.</div>}</section>
    <section style={{padding:"3.5rem 1rem",background:"#f6ead8"}}><div style={{maxWidth:1180,margin:"0 auto"}}><Heading tag="Thikana marketplace" title="Fresh listings from the community" to="/marketplace" label="Browse marketplace"/>{fresh.length?<div className="home-listing-grid" style={{display:"grid",gridTemplateColumns:"repeat(5,1fr)",gap:14}}>{fresh.map(listing=><Listing key={listing._id} listing={listing}/>)}</div>:<div style={{padding:28,background:"#fffaf3",borderRadius:14,color:"#80684b"}}>Community listings will appear here as sellers publish them. <Link to="/marketplace/sell" style={{color:"#9d6a27",fontWeight:700}}>Become a seller →</Link></div>}</div></section>
    <section style={{padding:"4rem 1rem",maxWidth:1180,margin:"0 auto"}}><Heading tag="What Savitri Livings offers" title="One place to shop, sell, learn and grow"/><div className="home-offers" style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:14}}>{offers.map(([Icon,title,text,to])=><Link key={title} to={to} style={{background:"white",border:"1px solid #eadbc7",borderRadius:15,padding:"1.25rem",color:"inherit",boxShadow:"0 4px 16px rgba(88,58,25,.05)"}}><div style={{width:40,height:40,borderRadius:12,display:"grid",placeItems:"center",background:"#f4dfba",color:"#855519"}}><Icon size={20}/></div><h3 style={{fontSize:"1.35rem",color:"#493015",margin:".9rem 0 .38rem"}}>{title}</h3><p style={{fontSize:".82rem",lineHeight:1.65,color:"#80684b"}}>{text}</p><span style={{display:"inline-flex",alignItems:"center",gap:4,color:"#9d6a27",fontSize:".78rem",fontWeight:700,marginTop:13}}>Explore <ArrowRight size={14}/></span></Link>)}</div></section>
    <style>{`@media(max-width:900px){.home-departments{grid-template-columns:repeat(3,1fr)!important}.home-hero{grid-template-columns:1fr!important}.home-product-grid{grid-template-columns:repeat(2,1fr)!important}.home-listing-grid{grid-template-columns:repeat(3,1fr)!important}.home-offers{grid-template-columns:repeat(2,1fr)!important}} @media(max-width:540px){.home-assurance{grid-template-columns:1fr!important;justify-items:start;padding-left:1rem}.home-listing-grid{grid-template-columns:repeat(2,1fr)!important}.home-offers{grid-template-columns:1fr!important}}`}</style>
  </main>;
}
