import { useEffect, useState } from "react";
import { Link, Navigate, useParams } from "react-router-dom";
import { MapPin, Plus, Search, Store } from "lucide-react";
import { marketplaceAPI } from "../../services/api.js";
import { useAuth } from "../../context/AuthContext.jsx";

const box = { background:"#fffdf9", border:"1px solid #ead8ba", borderRadius:16, boxShadow:"0 10px 28px rgba(89,60,29,.08)" };
const input = { width:"100%", border:"1px solid #d8c5a5", borderRadius:10, padding:".72rem .8rem", background:"#fffdf9", color:"#493015" };
const Card = ({ item }) => <Link to={`/marketplace/listing/${item._id}`} style={{ ...box, display:"block", overflow:"hidden", color:"inherit", textDecoration:"none" }}><div style={{ height:154, background:item.images?.[0] ? `#f4eadb url(${item.images[0]}) center/contain no-repeat` : "#f4eadb", display:"grid", placeItems:"center", color:"#a87735" }}>{!item.images?.[0] && <Store size={30}/>}</div><div style={{ padding:".9rem 1rem" }}><p style={{ color:"#9d6a27", textTransform:"uppercase", fontSize:".67rem", letterSpacing:".1em", fontWeight:700 }}>{item.category}</p><h3 style={{ color:"#38250f", fontSize:"1.25rem", margin:".25rem 0 .45rem" }}>{item.title}</h3><b style={{ color:"#79501d" }}>{item.price == null ? "Contact for price" : `₹${Number(item.price).toLocaleString("en-IN")}`}</b><p style={{ color:"#80684b", fontSize:".75rem", marginTop:8 }}><MapPin size={12} style={{ verticalAlign:"-2px" }}/> {item.location?.area || item.location?.city || "Kolkata"}</p></div></Link>;

export function MarketplaceHome() {
  const [categories,setCategories]=useState([]),[listings,setListings]=useState([]),[q,setQ]=useState(""),[category,setCategory]=useState(""),[loading,setLoading]=useState(true);
  const load=async(params={})=>{setLoading(true);try{setListings((await marketplaceAPI.listings(params)).data.listings)}finally{setLoading(false)}};
  useEffect(()=>{marketplaceAPI.categories().then(r=>setCategories(r.data.categories));load()},[]);
  return <main style={{ maxWidth:1160, margin:"0 auto", padding:"6.5rem 1rem 4rem" }}><section style={{ background:"linear-gradient(135deg,#f4e4c7,#d5ad6d)", border:"1px solid #d0a363", borderRadius:20, padding:"clamp(1.5rem,5vw,3.5rem)", color:"#38250f", marginBottom:30 }}><p className="section-tag" style={{ color:"#79501d" }}>Savitri Livings presents</p><h1 style={{ fontSize:"clamp(2.4rem,6vw,4.5rem)", margin:".4rem 0" }}>Thikana Marketplace</h1><p style={{ color:"#684d2b", maxWidth:580, lineHeight:1.7 }}>Discover local sellers, useful services and unique finds in one welcoming place.</p><form onSubmit={e=>{e.preventDefault();load({q,category})}} style={{ display:"flex", gap:8, marginTop:22, flexWrap:"wrap" }}><div style={{ flex:"1 1 230px", position:"relative" }}><Search size={16} style={{ position:"absolute",left:12,top:12,color:"#8d6a3b" }}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search marketplace" style={{...input,paddingLeft:36}}/></div><select value={category} onChange={e=>setCategory(e.target.value)} style={{...input,width:"auto",minWidth:160}}><option value="">All categories</option>{categories.map(c=><option key={c._id} value={c.slug}>{c.name}</option>)}</select><button className="btn-terra">Search</button></form></section><div style={{ display:"flex",justifyContent:"space-between",alignItems:"end",gap:14,flexWrap:"wrap",marginBottom:20 }}><div><p className="section-tag">Local and useful</p><h2 style={{color:"#38250f",fontSize:"2rem"}}>Fresh marketplace listings</h2></div><Link to="/marketplace/sell" className="btn-outline"><Plus size={16}/> Sell on Thikana</Link></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(220px,1fr))",gap:16}}>{loading?<p style={{color:"#80684b"}}>Loading listings…</p>:listings.length?listings.map(item=><Card key={item._id} item={item}/>):<div style={{...box,padding:28,gridColumn:"1/-1",textAlign:"center",color:"#80684b"}}>No listings yet. Be the first seller to post one.</div>}</div></main>;
}

export function ListingDetail(){const {id}=useParams();const [item,setItem]=useState(null);useEffect(()=>{marketplaceAPI.listing(id).then(r=>setItem(r.data.listing))},[id]);if(!item)return <main style={{padding:"8rem 1rem",textAlign:"center"}}>Loading listing…</main>;return <main style={{maxWidth:980,margin:"0 auto",padding:"6.5rem 1rem 4rem"}}><Link to="/marketplace" style={{color:"#9d6a27"}}>← Marketplace</Link><div className="market-detail" style={{display:"grid",gridTemplateColumns:"1fr .9fr",gap:28,marginTop:18}}><div style={{...box,minHeight:360,background:item.images?.[0]?`#f4eadb url(${item.images[0]}) center/contain no-repeat`:"#f4eadb"}}/><div><p className="section-tag">{item.category}</p><h1 style={{color:"#38250f",fontSize:"2.8rem"}}>{item.title}</h1><h2 style={{color:"#9d6a27",margin:".7rem 0 1.2rem"}}>{item.price==null?"Contact seller":`₹${Number(item.price).toLocaleString("en-IN")}`}</h2><p style={{color:"#6e573a",lineHeight:1.7}}>{item.description||"No description provided."}</p><div style={{...box,padding:15,marginTop:20}}><b>{item.sellerId?.marketplaceStoreName||item.sellerId?.fullName}</b><p style={{color:"#80684b",fontSize:".82rem",marginTop:5}}><MapPin size={13} style={{verticalAlign:"-2px"}}/> {item.location?.area||item.location?.city||"Kolkata"}</p></div></div></div><style>{`@media(max-width:700px){.market-detail{grid-template-columns:1fr!important}}`}</style></main>}

export function SellerHub(){const {isAuthenticated,user,refreshUser}=useAuth();const [mine,setMine]=useState([]),[categories,setCategories]=useState([]),[storeName,setStoreName]=useState(user?.marketplaceStoreName||""),[title,setTitle]=useState(""),[category,setCategory]=useState(""),[message,setMessage]=useState("");useEffect(()=>{marketplaceAPI.categories().then(r=>setCategories(r.data.categories));if(isAuthenticated)marketplaceAPI.myListings().then(r=>setMine(r.data.listings))},[isAuthenticated]);if(!isAuthenticated)return <Navigate to="/login" replace/>;const seller=!!user?.marketplaceStoreName||user?.role==="vendor";const makeSeller=async e=>{e.preventDefault();await marketplaceAPI.becomeSeller({storeName});await refreshUser();setMessage("Your seller profile is ready.")};const create=async e=>{e.preventDefault();await marketplaceAPI.createListing({title,category,subcategory:"general",location:{city:user?.city||"Kolkata"}});setMine((await marketplaceAPI.myListings()).data.listings);setTitle("");setMessage("Listing submitted for approval.")};return <main style={{maxWidth:900,margin:"0 auto",padding:"6.5rem 1rem 4rem"}}><p className="section-tag">Seller centre</p><h1 style={{color:"#38250f",fontSize:"2.8rem"}}>Sell through Thikana</h1>{message&&<p style={{background:"#f5e7cf",color:"#79501d",padding:12,borderRadius:10,marginTop:14}}>{message}</p>}{!seller?<form onSubmit={makeSeller} style={{...box,padding:22,maxWidth:500,marginTop:18}}><h2 style={{color:"#493015",fontSize:"1.5rem",marginBottom:12}}>Create your storefront</h2><input required value={storeName} onChange={e=>setStoreName(e.target.value)} placeholder="Business name" style={input}/><button className="btn-terra" style={{marginTop:12}}>Become a seller</button></form>:<><form onSubmit={create} className="seller-form" style={{...box,padding:18,display:"grid",gridTemplateColumns:"1fr 1fr auto",gap:10,marginTop:18}}><input required value={title} onChange={e=>setTitle(e.target.value)} placeholder="Listing title" style={input}/><select required value={category} onChange={e=>setCategory(e.target.value)} style={input}><option value="">Category</option>{categories.map(c=><option key={c._id} value={c.slug}>{c.name}</option>)}</select><button className="btn-terra">Submit</button></form><h2 style={{color:"#493015",fontSize:"1.8rem",margin:"28px 0 12px"}}>Your listings</h2>{mine.map(item=><div key={item._id} style={{...box,padding:14,marginBottom:8,display:"flex",justifyContent:"space-between"}}><b>{item.title}</b><span style={{color:"#80684b",textTransform:"capitalize"}}>{item.status}</span></div>)}</>}<style>{`@media(max-width:600px){.seller-form{grid-template-columns:1fr!important}}`}</style></main>}
